return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	init = function()
		vim.o.timeout = true
		vim.o.timeoutlen = 300
	end,
	opts = {
		preset = "helix",
		spec = {
			{
				mode = { "n", "v" },
				{ "<leader><tab>", group = "tabs" },
				{ "<leader>a", group = "ai" },
				{ "<leader>b", group = "buffer" },
				{ "<leader>c", group = "code" },
				{ "<leader>d", group = "debug" },
				{ "<leader>db", desc = "Toggle Breakpoint" },
				{ "<leader>dB", desc = "Conditional Breakpoint" },
				{ "<leader>dc", desc = "Continue" },
				{ "<leader>dC", desc = "Run to Cursor" },
				{ "<leader>di", desc = "Step Into" },
				{ "<leader>do", desc = "Step Out" },
				{ "<leader>dO", desc = "Step Over" },
				{ "<leader>dr", desc = "Toggle REPL" },
				{ "<leader>ds", desc = "Debug Script (script-runner)" },
				{ "<leader>dl", desc = "Debug Last Script" },
				{ "<leader>dt", desc = "Terminate" },
				{ "<leader>du", desc = "Debug UI" },
				{ "<leader>dv", desc = "Load VS Code Config" },
				{ "<leader>f", group = "file/find" },
				{ "<leader>g", group = "git" },
				{ "<leader>gh", group = "hunks" },
				{ "<leader>h", group = "help" },
				{ "<leader>q", group = "quit/session" },
				{ "<leader>s", group = "search" },
				{ "<leader>t", group = "term / run pkg script" },
				{ "<leader>tt", group = "terminal" },
				{ "<leader>tr", group = "script runner" },
				{ "<leader>trs", desc = "Run Script" },
				{ "<leader>trl", desc = "Run Last Script" },
				{ "<leader>trt", desc = "Run Test" },
				{ "<leader>trb", desc = "Run Build" },
				{ "<leader>trd", desc = "Debug Script" },
				{ "<leader>trD", desc = "Debug Last Script" },
				{ "<leader>tra", desc = "Attach to Debug" },
				{ "<leader>trp", desc = "Package Commands" },
				{ "<leader>u", group = "ui" },
				{ "<leader>w", group = "windows" },
				{ "<leader>x", group = "diagnostics/quickfix" },
				{ "g", group = "goto" },
				{ "gs", group = "surround" },
				{ "z", group = "fold" },
				{ "]", group = "next" },
				{ "[", group = "prev" },
			},
		},
	},
}
